---
title: "Parakeets"
output: html_notebook
---

```{r setup}
rm(list=ls())
setwd("/Users/jamese.richardson/Projects/Masters/stats_poster")
list.files()

library(tidyverse)
library(ggplot2)
library(vegan)
```

```{r}
birdData <- read_csv("birds.csv")
head(birdData)

birdDataCountsOnly <- birdData[birdData$count != 'X',]
birdDataCountsOnly$count_num <- as.numeric(birdDataCountsOnly$count)
```

```{r}
birdTable <- with(birdDataCountsOnly, tapply(count_num, list(site, species), FUN = mean, default=0))
head(birdTable)
```


```{r}
birdDataDf <- as.data.frame.matrix(birdTable)


library(data.table)
birdDataDf <- setDT(birdDataDf, keep.rownames = TRUE)[]
colnames(birdDataDf)[colnames(birdDataDf)=="rn"] <- "Site"
head(birdDataDf)
names(birdDataDf) <- make.names(names(birdDataDf), unique = TRUE)

birdDataDf
```


```{r}
parkData <- read_csv("parkdata.csv")
head(parkData)
allData <- inner_join(birdDataDf, parkData,by="Site")
head(allData)

write.csv(allData, file = "AllData.csv")
```

```{r}
names(allData)
```

species data: 2:10
env data: 12:15

```{r}
names(allData[2:10])
```

```{r}
names(allData[12:17])
```

```{r}
names(allData[,c(2,3,4,5,6,7,9,10)])
```

```{r}
spp.rich <- specnumber(allData[2:10], MARGIN=1) 
shannon <- diversity(allData[2:10])

spp.rich.no.parakeet <- specnumber(allData[,c(2,3,4,5,6,7,9,10)], MARGIN=1) 
shannon.no.parakeet <- diversity(allData[,c(2,3,4,5,6,7,9,10)])

enrichedData <- cbind(allData, spp.rich, shannon, spp.rich.no.parakeet, shannon.no.parakeet)
head(enrichedData)

enrichedData$has_parakeet <- ifelse(enrichedData$Ring.necked.Parakeet==0, "No", "Yes")

head(enrichedData)
```

```{r}
ggplot(enrichedData, aes(x=has_parakeet, y=shannon)) + 
  geom_boxplot()

```

```{r}

png("ParakeetPresense.png")
ggplot(enrichedData, aes(x=has_parakeet, y=shannon.no.parakeet)) + 
  geom_boxplot() +
  xlab("Are parakeets present?") + 
  ylab("Shannon index of cavity-nesting species (excl. parakeets)")
dev.off()
```

```{r}
shapiro.test(allData$Ring.necked.Parakeet) # p-value = 1.834e-11
shapiro.test(enrichedData$shannon.no.parakeet) # p-value = 0.02207

wilcox.test(enrichedData$shannon.no.parakeet ~ enrichedData$has_parakeet)

# W = 200, p-value = 0.01299
nrow(enrichedData)

pwr.t.test(power = NULL, d=0.5, n=56, sig.level=0.05, type = "one.sample", alternative = "two.sided")

mean(enrichedData[enrichedData$has_parakeet == 'Yes',]$shannon.no.parakeet) # 0.9866319
sd(enrichedData[enrichedData$has_parakeet == 'Yes',]$shannon.no.parakeet) # 0.4047124

mean(enrichedData[enrichedData$has_parakeet == 'No',]$shannon.no.parakeet) # 0.6449975
sd(enrichedData[enrichedData$has_parakeet == 'No',]$shannon.no.parakeet) #  0.4658505000



```



```{r}
ggplot(enrichedData, aes(x=has_parakeet, y=spp.rich)) + 
  geom_boxplot()

```
```{r}
ggplot(enrichedData, aes(x=has_parakeet, y=spp.rich.no.parakeet)) + 
  geom_boxplot()

```



```{r}
png("ParakeetAndSpeciesRichness.png")
ggplot(enrichedData, aes(x=Ring.necked.Parakeet, y=spp.rich.no.parakeet, color=Function)) + 
  geom_point() +
  xlab("Number of parakeets found") + 
  ylab("Speciess richness of cavity-nesting species (excl. parakeets)")
dev.off()
```

```{r}
cor.test(enrichedData$Ring.necked.Parakeet, enrichedData$spp.rich.no.parakeet, method="spearman")
# S = 13680, p-value = 2.401e-05, rho = 0.5324526 

```


```{r}
ggplot(enrichedData, aes(x=Ring.necked.Parakeet, y=spp.rich.no.parakeet)) + 
  geom_point()

cor.test(enrichedData$Ring.necked.Parakeet, enrichedData$spp.rich.no.parakeet, method="spearman")
```
```{r}
pwr.r.test(n=56,r=0.53,sig.level = 0.05)
s```

```{r}
names(enrichedData)
speciesShapiro <- sapply(enrichedData[2:10], shapiro.test)
speciesShapiro[2,]
```
```{r}
names(enrichedData)
envShapiro <- sapply(enrichedData[12:18], shapiro.test)
envShapiro[2,]
```

```{r}
enrichedData[12:18]
data.frame(sapply(enrichedData[12:18], sqrt))

envShapiroSqrt <- sapply(data.frame(sapply(enrichedData[12:18], sqrt)), shapiro.test)
envShapiroSqrt[2,]
```

```{r}
envLogDf <- data.frame(sapply(enrichedData[12:18], function(v) { l = log10(v); ifelse(v == -Inf, 0, v)}))
envShapiroLog <- sapply(envLogDf, shapiro.test)
envShapiroLog[2,]
```


```{r}
nmds <- metaMDS(enrichedData[2:10], k=2, trymax = 30) 

plot(nmds, display = "sites")
with(enrichedData, ordiellipse(nmds, has_parakeet, col=4, lwd=2, draw = "polygon", kind = c("sd"))) 
with(enrichedData, ordispider(nmds, has_parakeet, label=TRUE))
```

```{r}
  ef <- envfit(nmds, enrichedData[12:18], na.rm = TRUE, permu = 999) 
  ef
```

```{r}
nmds.no.parakeet <- metaMDS(enrichedData[,c(2,3,4,5,6,7,9,10)], k=2, trymax = 30) 

sim.type<-anosim(enrichedData[,c(2,3,4,5,6,7,9,10)], enrichedData$has_parakeet, permutations = 999, distance = "bray") 
summary(sim.type)

png("NMDS.png")
plot(nmds.no.parakeet, display = "sites")
with(enrichedData, ordiellipse(nmds.no.parakeet, has_parakeet, col=4, lwd=2, draw = "polygon", kind = c("sd"))) 
with(enrichedData, ordispider(nmds.no.parakeet, has_parakeet, label=TRUE))
dev.off()
```

```{r}
  ef.with.parakeets <- envfit(nmds.no.parakeet, enrichedData[,c(8,12,13,14,15,16,17,18)], na.rm = TRUE, permu = 999) 
  ef.with.parakeets
```

```{r}
sim.type<-anosim(enrichedData[,c(8,12,13,14,15,16,17,18)], enrichedData$has_parakeet, permutations = 999, distance = "bray") 
summary(sim.type)
```




```{r}
plot(nmds., display = "sites")
with(enrichedData, ordiellipse(nmds, has_parakeet, col=4, lwd=2, draw = "polygon", kind = c("sd")), label=T) 
plot(ef, p.max = 0.2)
with(enrichedData, ordispider(nmds, has_parakeet, label=TRUE))
```

```{r}
plot(nmds.no.parakeet, display = "sites")
with(enrichedData, ordiellipse(nmds.no.parakeet, has_parakeet, col=4, lwd=2, draw = "polygon", kind = c("sd"))) 
plot(ef.with.parakeets, p.max = 0.2)
with(enrichedData, ordispider(nmds.no.parakeet, has_parakeet, label=TRUE))
```


```{r}
sim.type<-anosim(enrichedData[12:18], enrichedData$has_parakeet, permutations = 999, distance = "bray") 
summary(sim.type)
```

```{r}
sim.type<-anosim(enrichedData[2:10], enrichedData$has_parakeet, permutations = 999, distance = "bray") 
summary(sim.type)
```


```{r}
nrow(enrichedData)
```

```{r}
library(pwr)
pwr.f2.test(u = 1, v = 55, f2 = 0.02, sig.level = 0.05)
```
```{r}
pwr.r.test(r=0.2, sig.level=0.05 ,alternative="two.sided", power=0.8)
```



presense / absence on spp.rich/shannon
abundance of parakeets on spp.rich/shannon

effect of presence/absense on community structure -> nmds -> include environmental?
ggplot presense/absense on abundance of each species. -> test each pair

altitude?


```{r}
names(enrichedData)
speciesPerRow <- gather(data=enrichedData, key=species, value=count,Common.Starling,Eurasian.Blue.Tit,European.Green.Woodpecker,Great.Spotted.Woodpecker,Great.Tit,Jackdaw,Stock.Dove,Tawny.Owl, factor_key=TRUE)
head(speciesPerRow)
```

```{r}
png("speciesData.png", width=800, height=480)
ggplot(speciesPerRow, aes(x=species, y=log10(count), fill=has_parakeet)) + 
  geom_boxplot(position = position_dodge()) +
  scale_x_discrete(labels = c("Starling", "Blue Tit", "Green Woodp.", "Great Spot. Woodp.", "Great Tit", "Jackdaw", "Stock Dove", "Tawny Owl")) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1), legend.position="bottom") +
  ylab("Log 10 of Count") + xlab("Species") +
  guides(fill=guide_legend(title="Are parakeets present?"))
dev.off()
```